services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php82-dev
    ports:
      - "${APACHE_PORT:-8080}:80"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
